//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonIPServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public int CallID { get; set; }
        public Nullable<int> CallerID { get; set; }
        public Nullable<int> ReceiverID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int Duration { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
